// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg_CKYkhFpxihcrTO3xo9EhFsRgG57wNY',
    appId: '1:978520616248:web:c509e7ccb49faa3ada25cd',
    messagingSenderId: '978520616248',
    projectId: 'my-project-bf988',
    authDomain: 'my-project-bf988.firebaseapp.com',
    storageBucket: 'my-project-bf988.appspot.com',
    measurementId: 'G-Y754WR9Q5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIEyuju43H6bpdqrtIiHsOfzz-zvxIcmE',
    appId: '1:978520616248:android:740901676416b134da25cd',
    messagingSenderId: '978520616248',
    projectId: 'my-project-bf988',
    storageBucket: 'my-project-bf988.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNwJK97YUmwlGD8WAJYlDV1H5CAFedc_U',
    appId: '1:978520616248:ios:1190701dae55939cda25cd',
    messagingSenderId: '978520616248',
    projectId: 'my-project-bf988',
    storageBucket: 'my-project-bf988.appspot.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNwJK97YUmwlGD8WAJYlDV1H5CAFedc_U',
    appId: '1:978520616248:ios:1190701dae55939cda25cd',
    messagingSenderId: '978520616248',
    projectId: 'my-project-bf988',
    storageBucket: 'my-project-bf988.appspot.com',
    iosBundleId: 'com.example.myProject',
  );
}
